# fly.toml app configuration file generated for covr-ocr-service on 2025-12-21T16:07:32-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'covr-ocr-service'
primary_region = 'iad'

[build]

[env]
  MAX_UPLOAD_MB = '10'
  OCR_DEFAULT_LANG = 'eng'
  OCR_DEFAULT_OEM = '1'
  OCR_DEFAULT_PSM = '3'
  OCR_MAX_SIDE = '1600'
  REQUEST_TIMEOUT_S = '15'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 50
    soft_limit = 25

  [[http_service.checks]]
    interval = '30s'
    timeout = '10s'
    grace_period = '10s'
    method = 'GET'
    path = '/healthz'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
